workflows:
  unsigned-ios:
    name: Unsigned iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      xcode: 15.2
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          pod install
      - name: Build archive
        script: |
          xcodebuild archive \
            -workspace "YourApp.xcworkspace" \
            -scheme "YourScheme" \
            -configuration Release \
            -archivePath build/YourApp.xcarchive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath build/YourApp.xcarchive \
            -exportPath build/ipa \
            -exportOptionsPlist ExportOptions.plist \
            CODE_SIGNING_ALLOWED=NO
    artifacts:
      - build/ipa/*.ipa
